load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "cav_regiment_34_cut",
    src = "cav_regiment_34_cut.scad",
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "cav_troop_3_mark",
    src = "cav_troop_3_mark.scad",
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)
