load("//tools:openscad.bzl", "openscad_library")

package(default_visibility = ["//visibility:public"])

openscad_library(
    name = "libinsert",
    srcs = ["libinsert.scad"],
    deps = ["//common:kow"],
)
