load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "cavalry_troop",
    src = "plain.scad",
    defines = {
        "unit_type": "\"cavalry\"",
        "unit_size": "\"troop\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "cavalry_regiment",
    src = "plain.scad",
    defines = {
        "unit_type": "\"cavalry\"",
        "unit_size": "\"regiment\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "infantry_troop",
    src = "plain.scad",
    defines = {
        "unit_type": "\"infantry\"",
        "unit_size": "\"troop\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "infantry_regiment",
    src = "plain.scad",
    defines = {
        "unit_type": "\"infantry\"",
        "unit_size": "\"regiment\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "lrginf_troop",
    src = "plain.scad",
    defines = {
        "unit_type": "\"lrginf\"",
        "unit_size": "\"troop\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "lrginf_regiment",
    src = "plain.scad",
    defines = {
        "unit_type": "\"lrginf\"",
        "unit_size": "\"regiment\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "monster",
    src = "plain.scad",
    defines = {
        "unit_type": "\"monster\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "titan",
    src = "plain.scad",
    defines = {
        "unit_type": "\"titan\"",
    },
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)
