load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_infantry_slot_45",
    defines = {"SLOTTA_ANGLE": "45"},
    module = "SlottaBM4",
    deps = [
        "//common:kow",
        "//miniature-bases:libbase",
    ],
)
