load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "cav_troop_4_mark",
    src = "cav_troop_4_mark.scad",
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "cav_troop_4_cut",
    src = "cav_troop_4_cut.scad",
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)
