load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_cavalry_slot",
    src = "bm4_cavalry_slot.scad",
    deps = [
        "//common:kow",
        "//miniature-bases:libbase",
    ],
)
