load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "insert_regiment_side_1.5",
    src = "insert_regiment_side_1.5.scad",
    deps = [
        "//TM4-inserts:libinsert",
        "//common:kow",
    ],
)
