load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "lrginf_horde_grid_2x1_base",
    src = "lrginf_horde_grid_2x1_base.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "lrginf_horde_grid_2x1_grid",
    src = "lrginf_horde_grid_2x1_grid.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)
