load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_infantry_slot",
    defines = {
        "SLOTTA_ANGLE": "0",
        "SLOTTA_SLOT_MARGIN": "1",
    },
    module = "SlottaBM4",
    deps = ["//miniature-bases:libbase"],
)
