load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "infantry_troop_34",
    src = "infantry_troop_34.scad",
    type = "stl",
    deps = [
        "//common:libtray",
    ],
)
