load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "inf_horde_full",
    src = "inf_horde_full.scad",
    type = "svg",
    deps = [
        "//common:libtray",
    ],
)
