load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_infantry_artizan",
    src = "bm4_infantry_artizan.scad",
    deps = [
        "//miniature-bases:libbase",
        "//common:kow",
    ],
)
