load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_infantry_artizan",
    src = "bm4_infantry_artizan.scad",
    defines = {
        "width": "9",
    },
    normalize = True,
    deps = [
        "//common:kow",
        "//miniature-bases:libbase",
    ],
)

openscad_artifact(
    name = "bm4_infantry_artizan_v2",
    src = "bm4_infantry_artizan.scad",
    defines = {
        "width": "13.5",
    },
    normalize = True,
    deps = [
        "//common:kow",
        "//miniature-bases:libbase",
    ],
)
