load("//tools:openscad.bzl", "openscad_library")

package(default_visibility = ["//visibility:public"])

openscad_library(
    name = "libbase",
    srcs = ["libbase.scad"],
    deps = ["//common:kow"],
)
