load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "bm4_infantry_slot_22",
    defines = {"SLOTTA_ANGLE": "22"},
    module = "SlottaBM4",
    deps = ["//miniature-bases:libbase"],
)
