load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "infantry_filler_8x1",
    src = "infantry_filler_8x1.scad",
    deps = [
        "//common:kow",
        "//miniature-bases:libbase",
    ],
)
