load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "insert_troop_side_0.5",
    src = "insert_troop_side_0.5.scad",
    deps = [
        "//TM4-inserts:libinsert",
    ],
)
