load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "inf_troop_full",
    src = "inf_troop_full.scad",
    type = "svg",
    deps = [
        "//common:libtray",
        "//common:kow",
    ],
)
