load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "insert_cav_regiment_34",
    src = "insert_cav_regiment_34.scad",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)
