load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "infantry_legion_grid_8x6_base",
    src = "infantry_legion_grid_8x6_base.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "infantry_legion_grid_8x6_grid",
    src = "infantry_legion_grid_8x6_grid.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)
