load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "infantry_horde_grid_8x3_base",
    src = "infantry_horde_grid_8x3_base.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)

openscad_artifact(
    name = "infantry_horde_grid_8x3_grid",
    src = "infantry_horde_grid_8x3_grid.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)
