load("//tools:openscad.bzl", "openscad_library")

package(default_visibility = ["//visibility:public"])

openscad_library(
    name = "kow",
    srcs = ["kow.scad"],
    deps = [":params"],
)

openscad_library(
    name = "params",
    srcs = ["params.scad"],
)
