package(default_visibility = ["//visibility:public"])

# load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

# # Import the sh_binary rule
# maybe(
#     name = "bazel_skylib",
#     module = "@bazel_skylib//lib:lib.bzl",
# )

# Define a new sh_binary rule for OpenSCAD
sh_binary(
    name = "openscad",
    srcs = ["openscad.sh"],
    deps = [
        # Add any necessary dependencies here
    ],
)
