load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "lrgcav_horde_23",
    src = "lrgcav_horde_23.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)

