load("//tools:openscad.bzl", "openscad_artifact")

openscad_artifact(
    name = "lrgcav_regiment_full",
    src = "lrgcav_regiment_full.scad",
    type = "svg",
    deps = [
        "//common:kow",
        "//common:libtray",
    ],
)
